name: E2E Tests Windows

on: [push]

jobs:
  test:
    runs-on: windows-2019

    # env:
    #   QAW_ARTIFACT_PATH: ${{ github.workspace }}\artifacts

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '12'

      - uses: actions/checkout@v2

      - run: npm install

      - run: npm run build

      - name: Start sandbox
        run: |
          start-process npm -ArgumentList "run test:server" -WindowStyle hidden
          npx wait-on http://localhost:5000

      - run: npm link && npm link qawolf

      - name: Test e2e
        run: |
          # Windows throws invalid js for linked binaries unless we call node directly
          node ./node_modules/qawolf test --all-browsers --headless --rootDir=./test/.qawolf

      # - name: Upload Artifacts
      #   if: always()
      #   uses: actions/upload-artifact@master
      #   with:
      #     name: qawolf
      #     path: ${{ github.workspace }}\artifacts

    timeout-minutes: 20
