name: npm test
on:
  push:
    branches:
      - master
  pull_request:
    branches: "*"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 25
      # build first to partition the action logs
      - name: Build
        uses: ./.github/actions/local-docker
        with:
          args: 'echo "Dockerfile built"'
      - name: Test
        uses: ./.github/actions/local-docker
        with:
          args: "cd $QAWOLF_DIR && npm test && npm run test:docker"
        env:
          QAW_SLEEP_MS: 0
          # needed for jest-environment test
          QAW_ENVIRONMENT_URL: http://theinternet:5000/
          QAW_TEST_URL: http://theinternet:5000/
      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@master
        with:
          name: qawolf
          path: "./artifacts"
    services:
      theinternet:
        image: gprestes/the-internet@sha256:f741ba048b7232ef90b0f7885de7f6ac42a52a17e73dd82afc484da140398796
    timeout-minutes: 20
