name: Unit Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [12.x]
        test: [lint, chromium, firefox, webkit]

    steps:
      - uses: actions/checkout@v2

      - name: Install chromium dependencies
        if: matrix.test == 'chromium'
        run: sudo apt-get install libgbm1

      - name: Install webkit dependencies
        if: matrix.test == 'webkit'
        run: |
          sudo apt-get install libwoff1 libopus0 libwebp6 libwebpdemux2 libenchant1c2a libgudev-1.0-0 libsecret-1-0 libhyphen0 libgdk-pixbuf2.0-0 libegl1 libgles2 libevent-2.1-6 libnotify4 libvpx5 libxslt1.1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm install

      - run: npm run lint
        if: matrix.test == 'lint'

      - run: npm run build

      - run: npm run test:server &
        if: matrix.test != 'lint'

      - run: npm link && npm link qawolf
        if: matrix.test != 'lint'

      - run: QAW_BROWSER=${{ matrix.test }} npm test
        if: matrix.test != 'lint'
        env:
          CI: true

    timeout-minutes: 20
