name: Chromium and Firefox Windows
on:
  push:
    branches:
      - master
  pull_request:
    branches: "*"
jobs:
  test:
    runs-on: windows-2019

    env:
      QAW_ARTIFACT_PATH: ${{ github.workspace }}\artifacts
      QAW_LOG_LEVEL: debug
      QAW_SLEEP_MS: 0
      QAW_TEST_URL: http://localhost:5000/

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: "12"

      - uses: actions/checkout@v2
        with:
          path: project

      - name: Build QA Wolf
        run: |
          cd project
          npm run bootstrap

      - uses: eregon/use-ruby-action@master
        with:
          ruby-version: "2.6.5"

      - name: Run "the-internet"
        run: |
          git clone https://github.com/qawolf/the-internet.git theinternet
          cd theinternet
          bundle install --quiet
          start-process bundle -ArgumentList "exec rackup --host 0.0.0.0 --port 5000" -WindowStyle hidden

      - name: Run tests on chromium
        run: |
          cd project
          npm run test:windows
        env:
          QAW_BROWSER: chromium

      - name: Run tests on firefox
        run: |
          cd project
          npm run test:windows
        env:
          QAW_BROWSER: firefox

      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@master
        with:
          name: qawolf
          path: ${{ github.workspace }}\artifacts

    timeout-minutes: 20
